# paths
train_path: "data/full.csv"
test_path: "data/cfcheck.csv"
model_path: "models/xgboost_hltprhc.pkl"
output_dir: "cf_outputs/gen1_models_explainers_constraints/random_search_exp"

# system config
backend: "sklearn"

# profile, eg. DiCE model
explainer_profile: "random"   # "random" or "genetic"
total_CFs: 10
stopping_threshold: 0.9
use_permitted_range: true
