# paths
test_path: "data/cfcheck.csv"
model_path: "models/rf_hltprhc.pkl"
output_dir: "cf_outputs"

# system config
target: "hltprhc"
backend: "sklearn"

# profile, eg. DiCE model
explainer_profile: "random"   # "random" or "genetic"


# if on large dataset, first 20
n_query_instances: 20
