# paths
train_path: "data/full.csv"
test_path: "data/cfcheck.csv"
model_path: "models/nn_hltprhc.keras"
output_dir: "cf_outputs"
scaler_path: "models/scaler.pkl"

# system config
target: "hltprhc"
backend: "TF2"

# profile, eg. DiCE model
explainer_profile: "gradient"
total_cfs: 20
stopping_threshold: None   # does not use
use_permitted_range: true  # Neural network with gradient descent handles permitted range well
