# paths
train_path: "data/full.csv"
test_path: "data/cfcheck.csv"
model_path: "models/rf_SMOTE_gridsearched.pkl"
output_dir: "cf_outputs/predictors_vs_threshold/SMOTE/gridsearched_predictors/"

# system config
backend: "sklearn"

# profile, eg. DiCE model
explainer_profile: "genetic"
total_CFs: 10
stopping_threshold: 0.5
use_permitted_range: true
