# paths
train_path: "data/full.csv"
test_path: "data/cfcheck.csv"
model_path: "models/rf_weighted.pkl"
output_dir: "cf_outputs/predictors_vs_threshold/weighted"

# system config
backend: "sklearn"

# profile, eg. DiCE model
explainer_profile: "genetic"
use_permitted_range: true
total_CFs: 10

# variables to vary
stopping_threshold: 0.9
